---
title: "HW2_Lian"
author: "Jiayi Lian"
date: "September 4, 2019"
output: pdf_document
---

# Homework2

## P3

It can help me know how far have you gone through in your project.I can also see what changes have been done after each version created. There is more convenience. If I am not satisfied with my final version, I am able to find proper immediate version to start. It would save my time to go back step by step.

## p4

```{r}
# Store url 
# In the order of "sensory data, gold medal performance, brain weight vs body weight, triplicate measurements of tomato."
url_sensory<-"http://www2.isye.gatech.edu/~jeffwu/wuhamadabook/data/Sensory.dat"
url_gold<-"http://www2.isye.gatech.edu/~jeffwu/wuhamadabook/data/LongJumpData.dat"
url_brain<-"http://www2.isye.gatech.edu/~jeffwu/wuhamadabook/data/BrainandBodyWeight.dat"
url_tomato<-"http://www2.isye.gatech.edu/~jeffwu/wuhamadabook/data/tomato.dat"
#download into local memory
Sensory<-read.csv(url_sensory,header =  F,skip = 2,sep = "")
#manipulate data into a tidy format
#transfer data into a vector
dim_ori<-dim(Sensory)
Sen_2=c()
for (i in 1:dim_ori[1]) {
  if (sum(i == seq(1,dim_ori[1],3)))
  {Sen_2=c(Sen_2,as.matrix(Sensory[i,2:dim_ori[2]]))}
  else
  {Sen_2=c(Sen_2,as.matrix(Sensory[i,1:(dim_ori[2]-1)]))}
}
#transfer the vector into a data.frame
Sen_2<-data.frame(matrix(Sen_2,nrow = dim_ori[1],ncol = dim_ori[2]-1))
#change the name of data
colnames(Sen_2)<-paste('Operator',as.character(1:5))

text_paste<-c()
for (i in 1:10) {
  text_paste<-c(text_paste,seq(i+0.1,i+0.3,0.1))
}
rownames(Sen_2)<-paste('Item',as.character(text_paste))
#Show table of Sensory data
Sen_2
```

```{r}
gold<-read.csv(url_gold,header =  F,skip = 1,sep = "")
dim_gold<-dim(gold)
dim_gold
gold_2=c()
for (i in 1:dim_gold[1]) {
  if (sum(i == c(5,6)))
  {gold_2=c(gold_2,as.matrix(gold[i,1:(dim_gold[2]-2)]))}
  else
  {gold_2=c(gold_2,as.matrix(gold[i,1:dim_gold[2]]))}
}
gold_2<-data.frame(matrix(gold_2,ncol = 2,nrow = 22,byrow = T))
colnames(gold_2)<-c('Year','Long Jump')
gold_2[1]<-gold_2[1]+1900
```

```{r}
?matrix
```
```{r}

```