---
title: "HW7_Lian_Jiayi"
author: "Jiayi Lian"
date: "October 4, 2019"
output: pdf_document
---

```{r setup, include=FALSE}

```

## P3
```{r}
# a
prop<-function(v){
  re<-sum(v==1)/length(v)
  return(re)
}

# b
set.seed(12345)
P4b_data <- matrix(rbinom(10, 1, prob = (30:40)/100), nrow = 10, ncol = 10, byrow = FALSE)

# c
apply(P4b_data, MARGIN=1, FUN=prop)
apply(P4b_data, MARGIN=2, FUN=prop)
```

The row proportions of sucess are equal to 1 or 0. And the column proportions are same.
Because each column of the matrix is copied from one vevtor.

```{r}
coin_sim<-function(p){
  v<-rbinom(10,1,prob = p)
  return(v)
}
# d
apply(as.matrix(seq(0.3,0.4,0.01)), MARGIN=1, FUN=coin_sim)

```

## P4
```{r}
device <- readRDS(file = "C:/Users/lianjiayi/Downloads/HW4_data.rds")
colnames(device)<-c("Observer","x","y")

spy_plot<-function(dat){
  name<-colnames(dat)
  plot(x=dat[,colnames(dat)[2]],y=dat[,colnames(device)[3]],xlab = name[2], ylab = name[3])
  
}
spy_plot(device)

by(device,INDICES=as.factor(device$Observer),FUN = spy_plot)
```

## P5
```{r}
#we are grabbing a SQL set from here
# http://www.farinspace.com/wp-content/uploads/us_cities_and_states.zip
#download the files, looks like it is a .zip
library(downloader)
download("http://www.farinspace.com/wp-content/uploads/us_cities_and_states.zip",dest="us_cities_states.zip")
unzip("./us_cities_states.zip")
    
#read in data, looks like sql dump, blah
library(data.table)
states <- fread(input = "./us_cities_and_states/states.sql",skip = 23,sep = "'", sep2 = ",", header = F, select = c(2,4))
### YOU do the CITIES
### I suggest the cities_extended.sql may have everything you need
### can you figure out how to limit this to the 50?
cities <- fread(input = "./us_cities_and_states/cities.sql",skip = 23,sep = "'", sep2 = ",", header = F, select = c(2,4))
# b
table(cities$V4)

freq_state<-as.data.frame(table(cities$V4))
# c
##pseudo code
letter_count <- data.frame(matrix(rep(0,50*26),nrow=50, ncol=26))
count_f<-function(v,let){
  count<-sum(v==let)
  return(count)
}
getCount <- function(state_name,letter){
  temp <- strsplit(state_name,split = "")
  count= sapply(letter, count_f, v=temp[[1]])
  return(count)
}
for(i in 1:50){
  letter_count[i,] <- sapply(states$V2[i],getCount,letter=c("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"))
}
# d
library(ggplot2)
library(fiftystater)
data("fifty_states") # this line is optional due to lazy data loading
# creat city table data
number_city<- data.frame(state = freq_state$Var1[1:50], freq=freq_state$Freq)
# map_id creates the aesthetic mapping to the state name column in your data
p1 <- ggplot(number_city, aes(map_id = state)) + 
# map points to the fifty_states shape data
      geom_map(aes(fill = freq), map = fifty_states) + 
      expand_limits(x = fifty_states$long, y = fifty_states$lat) +
      coord_map() +
      scale_x_continuous(breaks = NULL) + 
      scale_y_continuous(breaks = NULL) +
      labs(x = "", y = "") +
      theme(legend.position = "bottom", 
            panel.background = element_blank())


#Figure out states for highlight
mid<-apply(letter_count, MARGIN = 1, sum)
highlight<-data.frame(state=freq_state$Var1[1:50],high=ifelse(mid>3,10,1))


# map_id creates the aesthetic mapping to the state name column in your data
p2 <- ggplot(highlight, aes(map_id = state)) + 
# map points to the fifty_states shape data
      geom_map(aes(fill = high), map = fifty_states) + 
      expand_limits(x = fifty_states$long, y = fifty_states$lat) +
      coord_map() +
      scale_x_continuous(breaks = NULL) + 
      scale_y_continuous(breaks = NULL) +
      labs(x = "", y = "") +
      theme(legend.position = "bottom", 
            panel.background = element_blank())
    
p2
#ggsave(plot = p, file = "HW6_Problem6_Plot_Settlage.pdf")
```

Because packege fiftystates is not available for version 3.4.3 or other updating version. I just read the code posted and adjust it according to the requrement. It works in a lower version.
